sudo: required
services:
  - docker

before_install:
  - docker build -t zoro/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true zoro/docker-react npm run test -- --coverage
